services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # auto-register all controllers as services
    Pimcorecasts\Bundle\HashCash\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'controller.service_arguments' ]

    Pimcorecasts\Bundle\HashCash\Service\HashCashService:
        public: true

    # auto-register all controllers as services
    Pimcorecasts\Bundle\HashCash\Twig\HashCashTwigExtension:
        public: true
        tags: ['twig.extension']

    #
    # SECURITY
    #

    #
    # TEMPLATING
    #

    # auto-register all Helpers as services
#    Pimcorecasts\Bundle\StyleLabBundle\Services\:
#        public: true
#        resource: '../../Services'
